version: 2

sources:
  - name: hubspot
    database: colslaue
    schema: hubspot
    tables:
      - name: deal
      - name: company
      - name: deal_company
      - name: user

models:
  - name: hubspot__deals