version: 2

sources:
  - name: hubspot
    database: colslaue
    schema: hubspot
    tables:
      - name: deal
      - name: company
      - name: deal_company
      - name: user

models:
  - name: hubspot__deals
    description: 'all hubspot crm deals - one record per deal'
    columns:
      - name: deal_id
        description: 'primary key'
        tests:
          - unique
  - name: hubspot__companies
    description: 'all hubspot crm companies - one record per company'
    columns:
      - name: company_id
        description: 'primary key'
        tests:
          - unique
  - name: hubspot__users
    description: 'all hubspot crm users - one record per user'
    columns:
      - name: user_id
        description: 'primary key'
        tests:
          - unique
  - name: hubspot__company_overview
    description: 'report table describing hubspot crm companies with aggregates'
    columns:
      - name: company_id
        tests:
          - unique