version: 2

sources:
  - name: hubspot
    database: colslaue
    schema: hubspot
    tables:
      - name: deal
      - name: company
      - name: deal_company
      - name: user

models:
  - name: hubspot__deals
    description: 'all hubspot crm deals - one record per deal'
    columns:
      - name: deal_id
        description: 'primary key'
        tests:
          - unique